name: cupid_knot_assessment_test
description: Cupid Knots Assessment Test

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.5
  provider: ^6.0.2
  easy_container: ^1.0.3
  shared_preferences: ^2.0.13
  flutter_native_splash: ^2.1.2+1
  double_back_to_close_app: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans/ProductSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/ProductSans/ProductSans-Thin.ttf
          weight: 200
        - asset: assets/fonts/ProductSans/ProductSans-Light.ttf
          weight: 300
        - asset: assets/fonts/ProductSans/ProductSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/ProductSans/ProductSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/ProductSans/ProductSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/ProductSans/ProductSans-Black.ttf
          weight: 700
        - asset: assets/fonts/ProductSans/ProductSans-Black.ttf
          weight: 800
        - asset: assets/fonts/ProductSans/ProductSans-Black.ttf
          weight: 900